test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - pip install coverage
  - coverage run -m unittest discover -s test -p 'test_*.py'

build_image:
    image: docker:git
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/haydenh/bsc-awards .
        - docker push registry.gitlab.com/haydenh/bsc-awards:latest
    only:
        - master
