test:
  image: python:3
  script:
    - pip install -r requirements.txt
    - pip install coverage codecov
    - coverage run -m unittest discover -s test -p 'test_*.py'
    - codecov -t

build_image:
  stage: deploy
  image: docker:git
  services:
      - docker:dind
  script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
      - docker build -t registry.gitlab.com/haydenh/bsc-awards .
      - docker push registry.gitlab.com/haydenh/bsc-awards:latest
  only:
      - master
