image: docker:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - test
  - deploy

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -f Dockerfile.testing -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

test:
  stage: test
  services:
    - docker:dind
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker network create "net"
    - docker run --network "net" --name "db" -e "POSTGRES_PASSWORD=pass" -d "postgres"
    - docker run --network "net" --name "app" -v "$(pwd):/usr/src/app/" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths: [htmlcov/]

pages:
  stage: deploy
  allow_failure: true
  services:
    - docker:dind
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    - staging

build-master:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-staging:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:staging" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - staging
