test:
  image: python:3
  script:
    - pip install -r requirements.txt
    - pip install coverage codecov
    - coverage run -m unittest discover -s test -p 'test_*.py'
    - codecov -t $CODECOV_TOKEN

build_image:
  stage: deploy
  image: docker:git
  services:
      - docker:dind
  script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
      - docker build -t registry.gitlab.com/haydenh/bsc-awards .
      - docker push registry.gitlab.com/haydenh/bsc-awards:latest
  only:
      - master

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [codeclimate.json]
