services:
  - docker
language: python
install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python3 -m unittest discover -s test

after_success:
  - codecov

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t haydenhughes/bsc-awards:$TRAVIS_TAG -t haydenhughes/bsc-awards:latest  .
    - docker push haydenhughes/bsc-awards:$TRAVIS_TAG
    - docker push haydenhughes/bsc-awards:latest
  on:
    tags: true
