services:
  - docker
  - postgresql
language: python
install:
  - pip install -r requirements.txt
  - pip install codecov coverage

env:
  - DATABASE_URI=postgresql://postgres@127.0.0.1:5432

script:
  - coverage run -m unittest discover -s test

after_success:
  - codecov

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t haydenhughes/bsc-awards:$TRAVIS_TAG -t haydenhughes/bsc-awards:latest  .
    - docker push haydenhughes/bsc-awards:$TRAVIS_TAG
    - docker push haydenhughes/bsc-awards:latest
  on:
    tags: true
