version: '3'

services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_APP: awards

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
