FROM python:3.6.5

WORKDIR /usr/src/app

COPY testing_requirements.txt ./
RUN pip3 install --no-cache-dir -r testing_requirements.txt

CMD python3 -m coverage run -m unittest discover -s test && python3 -m coverage html && python3 -m coverage report
