version: '3'

services:
  app:
    image: haydenhughes/bsc-awards:latest
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - FLASK_APP=awards
      - FLASK_ENV=development
      - AWARDS_USERNAME=admin
      - AWARDS_PASSWORD=admin
      - DATABASE_URI=postgresql://postgres:pass@db/postgres

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
